name-template: 'ğŸš€ v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'ğŸ’¡ Features'
    label: 'feature'
  - title: 'ğŸ› Bug Fixes'
    label: 'bug'
  - title: 'ğŸ“¦ Misc Changes'
    label: 'documentation'

change-template: '- $TITLE #$NUMBER @$AUTHOR'
change-title-escapes: '\<*_&'

version-resolvers:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: 'path'

template: |
  ## ğŸš€ ì´ë²ˆ ë²„ì „ì—ì„œëŠ” ë¬´ì—‡ì´ ë°”ë€Œì—ˆì„ê¹Œìš”?
  ---
  $CHANGES

no-changes-template: 'ë³€ê²½ì‚¬í•­ì´ ì—†ì–´ìš”.. ğŸ˜'
